### ISSUE TITLE
Hypothese: Das Handelsvolumen der einzelnen Staaten hängt von der geographischen Nähe zum Handelpartner ab

### ISSUE THREAD

**Issue by BlkPingu** [BlkPingu/FreightDataAnalysis#9]
What are the reasons for being an export weak state?

**Comment by henniishappy** [comment]
Nullhypothese: Das Handelsvolumen der einzelnen Staaten hängt nicht von der geographischen Nähe zum Handelspartner ab

- Mexico und Canada einzeln anschauen
- eigentlich zwei Hypothesen
siehe #11

**Comment by henniishappy** [comment]
accidentally pushed everything as issue 10
